[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name="fa6-icons"
dynamic = ["version"]
description = "fontawesome 6 free icons as SVGs"
readme = "README.md"
requires-python=">=3.7"
license = {text = "Apache-2.0"}
authors = [{name = "Jeremy Howard", email = "github@jhoward.fastmail.fm"}]
keywords = ['nbdev', 'jupyter', 'notebook', 'python']
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = ["fastcore"]

[project.urls]
Repository = "https://github.com/AnswerDotAI/fa6-icons"
Documentation = "https://AnswerDotAI.github.io/fa6-icons"

[project.entry-points.nbdev]
fa6_icons = "fa6_icons._modidx:d"

[tool.setuptools.dynamic]
version = {attr = "fa6_icons.__version__"}

[tool.setuptools.packages.find]
include = ["fa6_icons"]

[tool.nbdev]
custom_sidebar = false
