# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fa6-icons',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/fa6-icons',
                'lib_path': 'fa6_icons'},
  'syms': { 'fa6_icons.core': { 'fa6_icons.core.HtmlNotStr': ('core.html#htmlnotstr', 'fa6_icons/core.py'),
                                'fa6_icons.core.HtmlNotStr._repr_html_': ('core.html#htmlnotstr._repr_html_', 'fa6_icons/core.py'),
                                'fa6_icons.core._dims': ('core.html#_dims', 'fa6_icons/core.py'),
                                'fa6_icons.core._name': ('core.html#_name', 'fa6_icons/core.py'),
                                'fa6_icons.core._svgs': ('core.html#_svgs', 'fa6_icons/core.py')},
            'fa6_icons.icons': {}}}
